spring:
  application:
    name: student-service
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: kamdoum
    password: danielle1234
    driver-class-name: org.postgresql.Driver
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.sql: debug

